# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-22 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateToday', models.DateField()),
                ('Period1', models.CharField(default='Free', max_length=10)),
                ('Period2', models.CharField(default='Free', max_length=10)),
                ('Period3', models.CharField(default='Free', max_length=10)),
                ('Period4', models.CharField(default='Free', max_length=10)),
                ('Period5', models.CharField(default='Free', max_length=10)),
                ('Period6', models.CharField(default='Free', max_length=10)),
                ('Period7', models.CharField(default='Free', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherSubject', models.CharField(max_length=20)),
                ('teacherClasses', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
