# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20180625_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teacherClasses',
            field=models.CharField(max_length=100),
        ),
    ]
